/// Hook trait definitions — the functional backbone of the new callback system.
///
/// Each trait represents a domain of agent lifecycle events with default no-op
/// implementations. `AgentCallbacks` holds `Option<Box<dyn Trait>>` instances,
/// making it easy to enable only the hooks you need.

// ---------------------------------------------------------------------------
// 1. AgentLoopHooks — Agent 整体循环
// ---------------------------------------------------------------------------

/// Agent loop lifecycle — fires once per run_loop invocation.
pub trait AgentLoopHooks: Send + Sync {
    /// Called when the agent loop starts (before any turns).
    fn on_loop_start(&self) {}
    /// Called when the agent loop ends (after all turns complete).
    /// `outcome` describes why the loop ended: "completed", "interrupted", "budget_exhausted", etc.
    fn on_loop_end(&self, _outcome: &str) {}
}

// ---------------------------------------------------------------------------
// 2. TurnLifecycleHooks — 单个 Turn 生命周期
// ---------------------------------------------------------------------------

/// Per-turn lifecycle — fires once per execute_turn call.
pub trait TurnLifecycleHooks: Send + Sync {
    /// Called before the turn cycle begins (budget check, compression prep).
    fn on_pre_turn(&self) {}
    /// Called after the turn cycle ends (all tool calls resolved or final response).
    /// `response` is the final text output. `success` indicates if the turn completed without error.
    fn on_post_turn(&self, _response: &str, _success: bool) {}
}

// ---------------------------------------------------------------------------
// 3. ApiLifecycleHooks — LLM API 调用
// ---------------------------------------------------------------------------

/// LLM API call lifecycle.
pub trait ApiLifecycleHooks: Send + Sync {
    /// Called before the API request is sent.
    fn on_api_call_start(&self) {}
    /// Called when the API request completes successfully.
    fn on_api_call_complete(&self) {}
    /// Called when the API request fails (after all retries exhausted).
    fn on_api_call_error(&self, _error: &str) {}
}

// ---------------------------------------------------------------------------
// 4. ToolLifecycleHooks — 工具执行
// ---------------------------------------------------------------------------

/// Tool execution lifecycle.
pub trait ToolLifecycleHooks: Send + Sync {
    /// Tool call generated by LLM (before execution).
    fn on_tool_gen(&self, _tool_name: &str, _call_id: &str) {}
    /// Tool execution begins.
    fn on_tool_start(&self, _tool_name: &str, _args: &str) {}
    /// Tool execution completes.
    fn on_tool_complete(&self, _tool_name: &str, _args: &str, _result: &str) {}
    /// Tool progress update (optional, for long-running tools).
    fn on_tool_progress(&self, tool_name: &str, preview: &str) {}
}

// ---------------------------------------------------------------------------
// 5. StreamingHooks — 流式输出
// ---------------------------------------------------------------------------

/// LLM output streaming events.
pub trait StreamingHooks: Send + Sync {
    /// Main response text delta.
    fn on_stream_delta(&self, text: &str) {}
    /// Thinking/reasoning text delta (from models that support it).
    fn on_thinking(&self, text: &str) {}
    /// Reasoning text delta (separate from thinking).
    fn on_reasoning(&self, text: &str) {}
    /// Interim assistant message (non-streaming, full text).
    fn on_interim_assistant(&self, text: &str) {}
}

// ---------------------------------------------------------------------------
// 6. SystemEventsHooks — 系统状态
// ---------------------------------------------------------------------------

/// System status and diagnostic events.
pub trait SystemEventsHooks: Send + Sync {
    /// Status message with level (e.g., "lifecycle", "warn", "info").
    fn on_status(&self, level: &str, message: &str) {}
    /// Step-by-step progress message.
    fn on_step(&self, message: &str) {}
    /// Verbose print — always visible even during streaming.
    fn on_vprint(&self, message: &str) {}
}

// ---------------------------------------------------------------------------
// 7. SessionLifecycleHooks — Session 生命周期
// ---------------------------------------------------------------------------

/// Session lifecycle events.
pub trait SessionLifecycleHooks: Send + Sync {
    /// Called when a session is rotated (compressed → parent ended, child created).
    /// `parent_id` is the old session, `child_id` is the new session.
    fn on_session_rotate(&self, parent_id: &str, child_id: &str) {}
    /// Called before context compression begins.
    fn on_compression_start(&self, message_count: usize) {}
    /// Called after context compression completes.
    /// `status` describes the result: "compacted", "unchanged", "ineffective".
    fn on_compression_complete(&self, status: &str) {}
}

// ---------------------------------------------------------------------------
// 8. InterruptLifecycleHooks — 中断事件
// ---------------------------------------------------------------------------

/// Interrupt lifecycle events.
pub trait InterruptLifecycleHooks: Send + Sync {
    /// Called when an interrupt is requested (user presses Ctrl+C).
    fn on_interrupt_requested(&self) {}
    /// Called when the turn actually responds to the interrupt.
    fn on_interrupted(&self, reason: &str) {}
}

// ---------------------------------------------------------------------------
// 9. CLIInteractionHooks — CLI 交互
// ---------------------------------------------------------------------------

/// CLI-specific interaction hooks.
pub trait CLIInteractionHooks: Send + Sync {
    fn on_print_prompt(&self) {}
    fn on_print_flush(&self) {}
    fn on_print_info(&self, message: &str) {}
    fn on_print_newline(&self) {}
    fn on_read_input(&self) -> Option<String> {
        None
    }
    fn on_should_exit(&self, input: &str) -> bool {
        false
    }
}

// ---------------------------------------------------------------------------
// 10. ClarificationHooks — 澄清请求
// ---------------------------------------------------------------------------

/// Clarification request — asks user for disambiguation.
pub trait ClarificationHooks: Send + Sync {
    fn on_clarify(&self, question: &str, choices: &[String]) -> String {
        String::new()
    }
}
