// Hook traits organized by kind. Each trait represents a domain of agent
// lifecycle events. HookEngine maintains separate queues per kind so that
// broadcast dispatch is precise and type-safe.

/// Hook base trait — all hooks carry id and priority metadata.
pub trait Hook: Send + Sync {
    fn id(&self) -> &str;
    fn priority(&self) -> u32 { 100 }
}

/// Agent loop lifecycle — fires once per run_loop invocation.
pub trait AgentLoopHooks: Hook {
    fn on_loop_start(&self) {}

    /// Called when the agent loop ends (after all turns complete).
    /// `outcome` describes why the loop ended: "completed", "interrupted", "budget_exhausted", etc.
    fn on_loop_end(&self, _outcome: &str) {}
}

/// Per-turn lifecycle — fires once per execute_turn call.
pub trait TurnLifecycleHooks: Hook {
    /// Called before the turn cycle begins (budget check, compression prep).
    fn on_pre_turn(&self) {}

    /// Called after the turn cycle ends (all tool calls resolved or final response).
    /// `response` is the final text output. `success` indicates if the turn completed without error.
    fn on_post_turn(&self, _response: &str, _success: bool) {}
}

/// Tool execution lifecycle.
pub trait ToolLifecycleHooks: Hook {
    /// Tool call generated by LLM (before execution).
    fn on_tool_gen(&self, _tool_name: &str, _call_id: &str) {}
    /// Tool execution begins.
    fn on_tool_start(&self, _tool_name: &str, _args: &str) {}
    /// Tool execution completes.
    fn on_tool_complete(&self, _tool_name: &str, _args: &str, _result: &str) {}
    /// Tool execution failed with an error.
    fn on_tool_error(&self, _tool_name: &str, _args: &str, _error: &str) {}
    /// Tool progress update (optional, for long-running tools).
    fn on_tool_progress(&self, _tool_name: &str, _preview: &str) {}
}

/// LLM output streaming events.
pub trait StreamingHooks: Hook {
    /// Main response text delta.
    fn on_stream_delta(&self, _text: &str) {}
    /// Thinking/reasoning text delta (from models that support it).
    fn on_thinking(&self, _text: &str) {}
    /// Reasoning text delta (separate from thinking).
    fn on_reasoning(&self, _text: &str) {}
    /// Interim assistant message (non-streaming, full text).
    fn on_interim_assistant(&self, _text: &str) {}
}

/// System status and diagnostic events.
pub trait SystemEventsHooks: Hook {
    /// Status message with level (e.g., "lifecycle", "warn", "info").
    fn on_status(&self, _level: &str, _message: &str) {}
}

/// Session lifecycle events.
pub trait SessionLifecycleHooks: Hook {
    /// Called when a session is rotated (compressed → parent ended, child created).
    /// `parent_id` is the old session, `child_id` is the new session.
    fn on_session_rotate(&self, _parent_id: &str, _child_id: &str) {}

    /// Called before context compression begins.
    fn on_compression_start(&self, _message_count: usize) {}

    /// Called after context compression completes.
    /// `status` describes the result: "compacted", "unchanged", "ineffective".
    fn on_compression_complete(&self, _status: &str) {}
}

/// Interrupt lifecycle events.
pub trait InterruptLifecycleHooks: Hook {
    /// Called when an interrupt is requested (user presses Ctrl+C).
    fn on_interrupt_requested(&self) {}

    /// Called when the turn actually responds to the interrupt.
    fn on_interrupted(&self, _reason: &str) {}
}
